name: data-preprocessing
on:
  push:
    branches: [workflows]
  pull_request:
    branches: [workflows]
jobs:
  data-preprocessing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Clean and preprocess data
      run: |
        python data/Data_Preprocessing.py
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        message: 'Cleaned and preprocessed data'
