name: Generate requirements.txt

on:
  push:
    branches:
      - workflows

jobs:
  generate-requirements:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate requirements.txt
      run: |
        pip install --upgrade pip
        pip freeze > requirements.txt

    - name: Commit requirements.txt
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Generate requirements.txt"
        file_pattern: requirements.txt
        commit_options: "--branch=workflows"
