name: Generate requirements.txt

on:
  push:
    branches:
      - main

jobs:
  generate-requirements:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate requirements.txt
      run: |
        pip install --upgrade pip
        pip freeze > requirements.txt

    - name: Commit requirements.txt
      run: |
        git config --global user.name "anthonyfyaacoub"
        git config --global user.email "ayaacoub.ieu2020@student.ie.edu"
        git checkout -b workflows
        git add requirements.txt
        git commit -m "Update requirements.txt"
        git push --set-upstream origin workflows
